### PR TITLE
Ice cream dataset exploration

### PR DESCRIPTION
**Pull request by dibble07**

### CODE REVIEW

**Comment by payoto** [comment]
Following this project really delivers, love the PR name 😂

**Comment by ChristopherSzczyglowski** [comment]
5 files changed, 15,000+ lines of diff - I am so triggered right now 😅
loving your work Dibble 👌

**Comment by dibble07** [comment]
@ChristopherSzczyglowski I haven't found the perfect way to deal with notebooks on git yet; this is the best I have. I submit notebooks with outputs cleared so that I can make meaningful diffs to previous versions. I then also have to have html versions which have the actual results in (and are more shareable with people that don't have a python environment) which is where we get silly amounts of line changes from.

**Comment by ChristopherSzczyglowski** [comment]
Sorry, I didn't mean that to come across as passive aggressive! Your
approach makes sense and I can see why you do it.

My only question is why do you version control the HTML results? I would
consider there artifacts of your build process (running the notebook) and
therefore totally reproducible given a functioning notebook and associated
python environment. You could  consider implementing a CI workflow where
you run all your notebooks and produce the HTML output as a build artifact
that is then made available separately (e.g. via a webpage hosted on
ReadTheDocs or similar). This way people that are just interested in the
results/docs can go to a non-code environment to receive these and you can
keep all the sexy technical stuff in your GitHub repo.

It might be that rerunning the notebooks is too time consuming, in which
case your approach seems like a good solution. This is just food for
thought and I'm sure you have already thought of something similar :)

**Comment by dibble07** [comment]
Don't worry. It didn't come across that way at all!
I guess it's not really about version controlling the results and more about having the results in the same place as the analyses so it's super easy to access/find. Our repo is more often for custom analyses with results than a reusable codebase.
I hadn't thought about hosting them. Are there free services you can use to do this? I know ReadTheDocs does this for code documentation but I didn't know you could host arbitrary html pages on it.

**Pull request merged**
